name: "Cache Invalidation"

on:
   workflow_dispatch:
      inputs:
         service-name:
            description: 'Service Name'     
            required: true
            default: client-user-promotion
         service-env:
            description: 'Service Environtment'     
            required: true
            type: choice
            options:
            - dev 
            - stage
            - test
            - prod
         brand-name:
            description: "Brand Name"
            required: true
            type: choice
            options:
            - global
            - wsop


permissions: write-all

jobs:
  invalidate-cache:
    # if: ${{ inputs.service-env == 'dev' }}
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Invalidatre Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEVOPS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVOPS }}
          AWS_DEFAULT_REGION: us-east-1
          aws_region: us-east-1
        run: |
          export distribution_id=$( aws cloudfront list-distributions --query 'DistributionList.Items[?Origins.Items[?Id==`"${{ inputs.service-name }}-${{ inputs.service-env }}.s3-website-'${aws_region}'.amazonaws.com"`]].{Id: Id}' --output text)
          aws cloudfront create-invalidation --distribution-id=$distribution_id --paths "/*"